tap "earthly/earthly"
tap "fewlines-education/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "thoughtbot/formulae"
brew "docker-compose", link: false
brew "gnupg"
brew "hivemind"
brew "jq"
brew "redis"
brew "mas"
brew "mkcert"
brew "nginx"
brew "flyctl"
brew "nss"
brew "yarn"
brew "earthly/earthly/earthly"
brew "fewlines-education/tap/sparta-cli", link: false
brew "thoughtbot/formulae/rcm"
brew "tldr"
cask "1password"
cask "clickup"
cask "docker"
cask "iterm2"
cask "postico"
cask "postman"
cask "slack"
cask "tableplus"
cask "visual-studio-code"
cask "spotify"
cask "zoom"
cask "firefox"
cask "obsidian"
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "WhatsApp", id: 1147396723
